asset_path: /home/user/rl_ws/urdf/generated/rl/openarm_gripper_bi_rl.urdf
usd_dir: /home/user/rl_ws/urdf/generated/rl/openarm_gripper_bi_rl
usd_file_name: openarm_gripper_bi_rl.usd
force_usd_conversion: true
make_instanceable: true
fix_base: true
root_link_name: null
link_density: 0.0
merge_fixed_joints: false
convert_mimic_joints_to_normal_joints: true
joint_drive:
  drive_type: force
  target_type: position
  gains:
    stiffness:
      .*: 100.0
      ^r_aj_1$: 70.0
      ^l_aj_1$: 70.0
      ^r_aj_2$: 70.0
      ^l_aj_2$: 70.0
      ^r_aj_3$: 70.0
      ^l_aj_3$: 70.0
      ^r_aj_4$: 60.0
      ^l_aj_4$: 60.0
      ^r_aj_5$: 10.0
      ^l_aj_5$: 10.0
      ^r_aj_6$: 10.0
      ^l_aj_6$: 10.0
      ^r_aj_7$: 10.0
      ^l_aj_7$: 10.0
      ^r_hj_gripper_1$: 5.0
      ^r_hj_gripper_2$: 5.0
      ^l_hj_gripper_1$: 5.0
      ^l_hj_gripper_2$: 5.0
    damping:
      .*: 1.0
      ^r_aj_1$: 2.75
      ^l_aj_1$: 2.75
      ^r_aj_2$: 2.5
      ^l_aj_2$: 2.5
      ^r_aj_3$: 2.0
      ^l_aj_3$: 2.0
      ^r_aj_4$: 2.0
      ^l_aj_4$: 2.0
      ^r_aj_5$: 0.7
      ^l_aj_5$: 0.7
      ^r_aj_6$: 0.6
      ^l_aj_6$: 0.6
      ^r_aj_7$: 0.5
      ^l_aj_7$: 0.5
      ^r_hj_gripper_1$: 0.1
      ^r_hj_gripper_2$: 0.1
      ^l_hj_gripper_1$: 0.1
      ^l_hj_gripper_2$: 0.1
collider_type: convex_decomposition
self_collision: false
replace_cylinders_with_capsules: false
collision_from_visuals: false
##
# Generated by UrdfConverter on 2026-09-05 at 20:11:13.
##
