asset_path: /home/user/rl_ws/urdf/generated/rl/openarm_dg5f-m_bi_rl.urdf
usd_dir: /home/user/rl_ws/urdf/generated/rl/openarm_dg5f-m_bi_rl
usd_file_name: openarm_dg5f-m_bi_rl.usd
force_usd_conversion: true
make_instanceable: true
fix_base: true
root_link_name: null
link_density: 0.0
merge_fixed_joints: false
convert_mimic_joints_to_normal_joints: false
joint_drive:
  drive_type: force
  target_type: position
  gains:
    stiffness:
      .*: 100.0
      ^r_aj_1$: 70.0
      ^l_aj_1$: 70.0
      ^r_aj_2$: 70.0
      ^l_aj_2$: 70.0
      ^r_aj_3$: 70.0
      ^l_aj_3$: 70.0
      ^r_aj_4$: 60.0
      ^l_aj_4$: 60.0
      ^r_aj_5$: 10.0
      ^l_aj_5$: 10.0
      ^r_aj_6$: 10.0
      ^l_aj_6$: 10.0
      ^r_aj_7$: 10.0
      ^l_aj_7$: 10.0
      ^l_hj_thumb_1$: 1.5
      ^l_hj_thumb_2$: 1.5
      ^l_hj_thumb_3$: 1.5
      ^l_hj_thumb_4$: 1.5
      ^l_hj_index_1$: 1.5
      ^l_hj_index_2$: 1.5
      ^l_hj_index_3$: 1.5
      ^l_hj_index_4$: 1.5
      ^l_hj_middle_1$: 1.5
      ^l_hj_middle_2$: 1.5
      ^l_hj_middle_3$: 1.5
      ^l_hj_middle_4$: 1.5
      ^l_hj_ring_1$: 1.5
      ^l_hj_ring_2$: 1.5
      ^l_hj_ring_3$: 1.5
      ^l_hj_ring_4$: 1.5
      ^l_hj_pinky_1$: 1.5
      ^l_hj_pinky_2$: 1.5
      ^l_hj_pinky_3$: 1.5
      ^l_hj_pinky_4$: 1.5
      ^r_hj_thumb_1$: 1.5
      ^r_hj_thumb_2$: 1.5
      ^r_hj_thumb_3$: 1.5
      ^r_hj_thumb_4$: 1.5
      ^r_hj_index_1$: 1.5
      ^r_hj_index_2$: 1.5
      ^r_hj_index_3$: 1.5
      ^r_hj_index_4$: 1.5
      ^r_hj_middle_1$: 1.5
      ^r_hj_middle_2$: 1.5
      ^r_hj_middle_3$: 1.5
      ^r_hj_middle_4$: 1.5
      ^r_hj_ring_1$: 1.5
      ^r_hj_ring_2$: 1.5
      ^r_hj_ring_3$: 1.5
      ^r_hj_ring_4$: 1.5
      ^r_hj_pinky_1$: 1.5
      ^r_hj_pinky_2$: 1.5
      ^r_hj_pinky_3$: 1.5
      ^r_hj_pinky_4$: 1.5
    damping:
      .*: 1.0
      ^r_aj_1$: 2.75
      ^l_aj_1$: 2.75
      ^r_aj_2$: 2.5
      ^l_aj_2$: 2.5
      ^r_aj_3$: 2.0
      ^l_aj_3$: 2.0
      ^r_aj_4$: 2.0
      ^l_aj_4$: 2.0
      ^r_aj_5$: 0.7
      ^l_aj_5$: 0.7
      ^r_aj_6$: 0.6
      ^l_aj_6$: 0.6
      ^r_aj_7$: 0.5
      ^l_aj_7$: 0.5
      ^l_hj_thumb_1$: 0.0
      ^l_hj_thumb_2$: 0.0
      ^l_hj_thumb_3$: 0.0
      ^l_hj_thumb_4$: 0.0
      ^l_hj_index_1$: 0.0
      ^l_hj_index_2$: 0.0
      ^l_hj_index_3$: 0.0
      ^l_hj_index_4$: 0.0
      ^l_hj_middle_1$: 0.0
      ^l_hj_middle_2$: 0.0
      ^l_hj_middle_3$: 0.0
      ^l_hj_middle_4$: 0.0
      ^l_hj_ring_1$: 0.0
      ^l_hj_ring_2$: 0.0
      ^l_hj_ring_3$: 0.0
      ^l_hj_ring_4$: 0.0
      ^l_hj_pinky_1$: 0.0
      ^l_hj_pinky_2$: 0.0
      ^l_hj_pinky_3$: 0.0
      ^l_hj_pinky_4$: 0.0
      ^r_hj_thumb_1$: 0.0
      ^r_hj_thumb_2$: 0.0
      ^r_hj_thumb_3$: 0.0
      ^r_hj_thumb_4$: 0.0
      ^r_hj_index_1$: 0.0
      ^r_hj_index_2$: 0.0
      ^r_hj_index_3$: 0.0
      ^r_hj_index_4$: 0.0
      ^r_hj_middle_1$: 0.0
      ^r_hj_middle_2$: 0.0
      ^r_hj_middle_3$: 0.0
      ^r_hj_middle_4$: 0.0
      ^r_hj_ring_1$: 0.0
      ^r_hj_ring_2$: 0.0
      ^r_hj_ring_3$: 0.0
      ^r_hj_ring_4$: 0.0
      ^r_hj_pinky_1$: 0.0
      ^r_hj_pinky_2$: 0.0
      ^r_hj_pinky_3$: 0.0
      ^r_hj_pinky_4$: 0.0
collider_type: convex_hull
self_collision: false
replace_cylinders_with_capsules: false
collision_from_visuals: false
##
# Generated by UrdfConverter on 2026-09-09 at 00:29:09.
##
