#!/usr/bin/env python3
"""Generate the DG5F "short" xacro fragments from the vendor CAD URDFs.

The short hand is the DG-5F with a shortened mount/base section: the finger
chains are identical to the DG5F (same ``{l,r}j_dg_*`` names, origins, axes and
limits), only ``*j_dg_palm`` moves from z=0.0698 to z=0.022 and the mount/base
masses and meshes change. So no renaming and no adapter synthesis is needed -
unlike ``gen_dg5fs_xacro.py``, this tool only has to do two things:

1. Rewrite the vendor mesh URIs. The ``vendor/tesollo_model`` release ships
   ``package://meshes/...``, which no ROS package resolves; ``ASSET_ROOTS`` in
   ``generate_rl_urdf.py`` resolves ``package://tesollo_model/...``.
2. Prepend the ``{side}_base_link`` adapter header that
   ``eef/tesollo_*_wrapper.xacro`` and ``tools/generate_rl_urdf.py`` expect,
   matching ``dg_description``'s ``dg5f_{side}.xacro``.

★Source choice: this reads ``vendor/tesollo_model`` (the CAD release), NOT the
``dg_description`` / ``dg5f_ros2`` driver copies. Those ship the same short
hand with rounded placeholder masses (1.685 kg, inconsistent with their own
inertia tensors) and a different set of joint limits on 9 joints. The CAD
release is mass/inertia consistent (1.570 kg per hand) and is the single
source for this asset's geometry, mass and limits.
"""

from __future__ import annotations

import re
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "vendor" / "tesollo_model" / "dg5f"
OUT_DIR = ROOT / "eef" / "dg5f_short"

MESH_URI_RE = re.compile(r"^package://meshes/(?P<rel>.+)$")

SIDE_CONFIG = {
    "right": {"link_prefix": "rl", "adapter_joint": "dummy_joint"},
    "left": {"link_prefix": "ll", "adapter_joint": "base_joint2"},
}


def rewrite_mesh_uri(uri: str) -> str:
    match = MESH_URI_RE.match(uri)
    if match is None:
        raise ValueError(f"unexpected mesh uri: {uri}")
    return f"package://tesollo_model/dg5f/meshes/{match.group('rel')}"


def convert_side(side: str) -> Path:
    cfg = SIDE_CONFIG[side]
    link_prefix = cfg["link_prefix"]
    source_name = f"dg5f_{side}_short.urdf"
    root = ET.parse(SOURCE_DIR / source_name).getroot()

    for element in root.iter("mesh"):
        filename = element.get("filename")
        if filename:
            element.set("filename", rewrite_mesh_uri(filename))

    out_root = ET.Element("robot", {"name": f"dg5f_{side}_short"})
    out_root.append(ET.Comment(
        f" GENERATED by tools/gen_dg5f_short_xacro.py from "
        f"vendor/tesollo_model/dg5f/{source_name} - do not edit. "
    ))

    ET.SubElement(out_root, "link", {"name": f"{side}_base_link"})
    adapter_joint = ET.SubElement(
        out_root, "joint", {"name": cfg["adapter_joint"], "type": "fixed"})
    ET.SubElement(adapter_joint, "origin", {"xyz": "0 0 0", "rpy": "0 0 0"})
    ET.SubElement(adapter_joint, "parent", {"link": f"{side}_base_link"})
    ET.SubElement(adapter_joint, "child", {"link": f"{link_prefix}_dg_mount"})

    for child in list(root):
        out_root.append(child)

    ET.indent(out_root, space="  ")
    out_path = OUT_DIR / f"dg5f_{side}_short.xacro"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    ET.ElementTree(out_root).write(out_path, encoding="unicode", xml_declaration=True)
    return out_path


def generate_all() -> dict[str, Path]:
    return {side: convert_side(side) for side in SIDE_CONFIG}


def main() -> int:
    for side, path in generate_all().items():
        print(f"generated {path.relative_to(ROOT)} ({side})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
