#!/usr/bin/env python3
"""Generate RL-only canonical URDFs and joint-order manifests.

The source URDFs keep vendor/controller names. These generated URDFs rename
links and joints into a stable RL schema so Isaac/RL code can use one action
and observation convention across different end-effectors.
"""

from __future__ import annotations

import argparse
import copy
import json
import math
import re
import sys
import xml.etree.ElementTree as ET
from collections import OrderedDict
from pathlib import Path
from typing import Iterable

sys.path.insert(0, str(Path(__file__).resolve().parent))
from crop_body_plate import ensure_cropped_meshes  # noqa: E402
from crop_link7_flange import ensure_link7_flange_mesh  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "generated" / "rl"
ASSET_ROOTS = {
    "openarm_description": ROOT / "vendor" / "openarm_description",
    "dg_description": ROOT / "vendor" / "delto_m_ros2" / "dg_description",
    "tesollo_model": ROOT / "vendor" / "tesollo_model",
    "RH56F1": ROOT / "vendor" / "RH56F1",
}

# The vendor body mesh includes an 8mm mount plate below z=0 of the new robot
# origin (origin = plate top). Everything defined in the vendor frame moves
# down by this amount; cropped meshes from crop_body_plate.py are pre-shifted.
BASE_LIFT_M = 0.008

# The stock link7 meshes include the stock-gripper motor section that is
# physically removed when a hand replaces the stock gripper, so RL assets swap
# them for the pre-cropped variants. The hand mount then sits on the exposed
# flange plate plane (z=0.0495, the large flat surface); the flange bolts
# protrude 4mm further (to z=0.0535, the cropped mesh top) and insert into the
# adapter plate holes, so they are NOT the mounting plane.
STOCK_LINK7_MESH_SWAP = {
    "link7.dae": "link7_without_mat2_mat3_components00_03.dae",
    "link7_symp.stl": "link7_without_mat2_mat3_components00_03.stl",
}
ARM_FLANGE_LINKS = {"r_al_7", "l_al_7"}
LINK7_FLANGE_Z = 0.0495

# RH56F1 vendor collision meshes are unrepairably non-watertight (asymmetric
# across sides; e.g. plam_1 euler=-72), so their finger-chain collisions are
# replaced with primitives fitted to the scaled mesh AABB: elongated segments
# become inscribed cylinders (radius from the SMALLEST cross extent - the
# shells nest closely, a circumscribed fit interpenetrates the neighbours),
# pads/tips become boxes. palm_2/palm_3 are watertight and keep their meshes.
# palm_1 is the back cover whose volume palm_2/palm_3 already envelop; a box
# fit swallows the finger roots (>15mm), so its collision is dropped entirely.
# Visual geometry is untouched.
RH_PRIMITIVE_SUFFIXES = tuple(
    [f"thumb_{i}" for i in range(1, 5)]
    + [f"{finger}_{i}" for finger in ("index", "middle", "ring", "pinky") for i in (1, 2)]
    + [f"{finger}_{kind}" for finger in ("thumb", "index", "middle", "ring", "pinky")
       for kind in ("sensor", "tip")]
)
RH_PRIMITIVE_LINKS = {f"{s}_hl_{suffix}" for s in ("r", "l") for suffix in RH_PRIMITIVE_SUFFIXES}
RH_DROP_COLLISION_LINKS = {f"{s}_hl_palm_1" for s in ("r", "l")}
# Above this longest/second-longest extent ratio a cylinder fits better than a box.
RH_CYLINDER_ELONGATION = 1.6

# ★2026-09-05: head_v1 (Fusion "rl_ws / simulation setting") replaces the old
#   head_realsense_d435i. vendor/head_v1 is GENERATED by tools/import_head_v1.py from
#   hdgp/assets/simulation_setting/head_v1 — re-run that tool, never edit it by hand.
HEAD_DIR = ROOT / "vendor" / "head_v1"
HEAD_URDF = HEAD_DIR / "urdf" / "head.urdf"
HEAD_DATA = HEAD_DIR / "head_data.json"
# Head base mounts on body_link at z=+750mm from the robot origin (mount top).
# ⚠2026-09-05: the camera chain sees the table ~21 mm too high with this value and
#   the hand-eye cannot observe a base→neck z error (it is absorbed into the board
#   pose). 0.750 matches the vendor body CAD pocket, but the physical mount height
#   (plate top → head base plate bottom = 0.730 here) is unverified — measure it
#   (B4) and update this ONE constant; sim2real reads the generated URDF.
HEAD_MOUNT_XYZ = "0 0 0.750"
HEAD_LINK_MAP = {
    "base_link": "head_base",
    "mid_link": "head_mid",
    "camera_link": "head_camera",
}
HEAD_JOINT_MAP = {
    "joint_pan": "head_j_pan",
    "joint_tilt": "head_j_tilt",
}
HEAD_LINK_ORDER = ["head_base", "head_mid", "head_camera", "head_cam_view"]
HEAD_JOINT_ORDER = ["head_j_mount", "head_j_pan", "head_j_tilt", "head_j_cam_view"]

# Camera view origin: the D435i **RGB (color) lens** in the head_camera link
# frame, read from head_v1's Fusion geometry (head_data.json, optical frames
# measured from the front apertures; see HEAD_RGB_LENS_FRAME for which aperture
# the RGB lens really is). +X is the viewing direction, +Z up (NOT the ROS optical
# orientation — consumers apply that themselves). The values are exported to
# each manifest (camera_view_frame + camera_optical_frames) so sim code can
# attach a camera even when USD import merges the fixed frame away.
# (previous head: front-glass centre (0.0147, 0.0145, 0.0365))
def _load_head_optical_frames() -> dict[str, tuple[float, float, float]]:
    data = json.loads(HEAD_DATA.read_text(encoding="utf-8"))
    frames = data["optical_frames_in_camera_link"]
    return {name: tuple(float(v) for v in frames[name]["xyz"]) for name in sorted(frames)}


HEAD_OPTICAL_FRAMES = _load_head_optical_frames()
# ★2026-09-05 hand-eye 재계산(sim2real/scripts/calib/solve_head_cad_prior.py): the D435i RGB
#   lens is the aperture the Fusion export labelled `ir_projector_frame` (y +0.0326 in
#   camera_link), NOT `color_frame` (y -0.0115). With that aperture the CAD chain fits the
#   25-pose hand-eye at 1.86 px (color_frame: 5.94 px) and puts the table at 0.204 (tape
#   0.205); the home-pose real photo vs sim render agree to 3-8 px on the plate bolt
#   pattern (our_source/head_check_0905). The USD keeps the Fusion labels, so consumers
#   attaching a camera to the grafted head_v1 prims must use THIS frame name.
HEAD_RGB_LENS_FRAME = "ir_projector_frame"
HEAD_CAM_VIEW_XYZ = HEAD_OPTICAL_FRAMES[HEAD_RGB_LENS_FRAME]
HEAD_CAM_VIEW_RPY = (0.0, 0.0, 0.0)


def _load_head_base_plate_bottom_z() -> float:
    """z of the head_v1 base plate underside in the head_base frame (-0.020)."""
    data = json.loads(HEAD_DATA.read_text(encoding="utf-8"))
    return float(data["links"]["base_link"]["visual_aabb_local_m"][0][2])


HEAD_MOUNT_Z = float(HEAD_MOUNT_XYZ.split()[2])
# ★2026-09-05: the vendor body's shoulder housing / head pocket (z 0.605-0.765) was
#   built around the OLD vendor head; head_v1 brings its own base plate, so the body
#   geometry is cut at the plate underside (0.730 for mount 0.750) - otherwise body_link
#   and the head links interpenetrate at rest. Derived, not a constant: moving the head
#   (B4 measurement) moves the cut with it (crop_body_plate.py names the file by height).
BODY_TOP_CROP_Z = HEAD_MOUNT_Z + _load_head_base_plate_bottom_z()

# Collider policy for the USD build (2026-09-05 user decision): OpenArm-made links
# (body, arms, head mount, stock gripper) get plain convex hulls; dexterous hand links
# (DG-5F / DG-5F-S / RH56F1) keep convex decomposition. Exported per asset in the
# manifest (`collision_approximation`) so tools/build_usd.py never guesses.
OPENARM_HULL_LINK_PREFIXES = ("body_link", "head_", "r_al_", "l_al_", "r_hl_gripper_", "l_hl_gripper_")

# ★★2026-09-09 **기본 골자**: collision 근사의 기본값은 **벤더가 검증한 구성**이다.
#   근거는 벤더 자신의 Isaac 변환 설정 — Tesollo 가 덤프한 `UrdfConverterCfg`:
#     vendor/delto_m_ros2/dg_isaacsim/dg5f_telop/rb10_1300e_dg5f_{left,right}/config.yaml
#     → `collider_type: convex_hull`
#   09.05 에 우리가 고른 `convex_decomposition` 은 비벤더 선택이었고, 그 결과 손 두 개가
#   로봇 collision shape 731개 중 ~710개를 차지했다. hull 로 굽자 **75개**가 됐고 부팅
#   PhysX contact-buffer overflow 가 사라졌으며, 자기충돌을 켤 수 있는 전제가 됐다.
#
#   ⇒ **새 로봇은 아무것도 선언하지 않으면 hull 로 만들어진다.** decomposition 이 필요한
#     자산만 사유와 함께 아래에 등록한다(사유 없는 등록은 금지 — 왜 벤더에서 벗어나는지가
#     자산과 함께 남아야 한다).
DEFAULT_COLLIDER = "convex_hull"
COLLIDER_DEVIATIONS: dict[str, tuple[str, str]] = {
    "openarm_rh56f1_bi": (
        "convex_decomposition",
        "self_collision_allowlist 의 `accept_raw` 항목들이 decomposition 임포트를 전제로 "
        "수용된 것이다(RH56F1 은 껍데기가 겹치는 설계). hull 로 바꾸려면 그 전제부터 재측정.",
    ),
    "openarm_gripper_bi": (
        "convex_decomposition",
        "좌 그리퍼 조는 **파지 도구**라 hull 이 되면 개구(84.5mm 실측)와 파지 대역"
        "(10~85mm)이 무효가 된다(write_collider_manifest.py 도크). 09.09 미검증 — 보류.",
    ),
}


def collider_default(asset: str) -> str:
    """자산의 collision 근사. 기본은 벤더 검증값(hull), 벗어나면 사유가 있어야 한다."""
    deviation = COLLIDER_DEVIATIONS.get(asset)
    if deviation is None:
        return DEFAULT_COLLIDER
    value, reason = deviation
    if not reason.strip():
        raise RuntimeError(f"{asset}: COLLIDER_DEVIATIONS 항목에 사유가 없다 — 벤더 이탈은 사유 필수")
    return value


def convex_hull_links(root: ET.Element) -> list[str]:
    """Links with mesh colliders that the USD build converts to convex hulls."""
    names = []
    for link in root.findall("link"):
        name = link.get("name") or ""
        if not name.startswith(OPENARM_HULL_LINK_PREFIXES):
            continue
        if any(c.find("geometry/mesh") is not None for c in link.findall("collision")):
            names.append(name)
    return names

# ★2026-09-05 asset line-up: four bimanual assets, one per end-effector. The key is
#   the asset name (hdgp/assets/robot/<key>_rl/); the value is the composed source.
#     openarm_dg5f-m_bi   Tesollo DG-5F   (vendor/delto_m_ros2 dg_description), both hands
#     openarm_dg5f-m-short_bi
#                         Tesollo DG-5F, short mount/base (vendor/tesollo_model
#                         dg5f, the CAD release), both hands. Same finger chain and
#                         joint names as openarm_dg5f-m_bi; *_dg_palm sits 47.8mm
#                         closer to the flange and the CAD masses/limits differ from
#                         the driver copies - see tools/gen_dg5f_short_xacro.py.
#     openarm_dg5f-s_bi   Tesollo DG-5F-S (vendor/tesollo_model dg5fs),          both hands
#     openarm_rh56f1_bi   Inspire RH56F1,                                        both hands
#     openarm_gripper_bi  stock OpenArm 2-finger gripper (openarm_hand),         both hands
#                         (source made by tools/gen_gripper_bi_source.sh)
#   The pre-09.05 assets (openarm_tesollo_sensor / openarm_tesollo_bi / openarm_tesollo_bi_s /
#   openarm_bi_rh56f1) are no longer generated; their generated/rl/*_rl.{urdf,yaml} stay on
#   disk, frozen, for the sim2real scripts that still read them.
SOURCES = OrderedDict(
    [
        ("openarm_dg5f-m_bi", ROOT / "generated" / "source" / "openarm_tesollo_bi.urdf"),
        ("openarm_dg5f-m-short_bi", ROOT / "generated" / "source" / "openarm_tesollo_bi_short.urdf"),
        ("openarm_dg5f-s_bi", ROOT / "generated" / "source" / "openarm_tesollo_bi_s.urdf"),
        ("openarm_rh56f1_bi", ROOT / "generated" / "source" / "openarm_bi_rh56f1.urdf"),
        ("openarm_gripper_bi", ROOT / "generated" / "source" / "openarm_gripper_bi.urdf"),
    ]
)


def asset_robot_name(source_name: str) -> str:
    """URDF <robot name>: the asset name, USD-prim safe (no '-')."""
    return f"{source_name.replace('-', '_')}_rl"

FINGER_NAMES = ["thumb", "index", "middle", "ring", "pinky"]
TESOLLO_FINGER_BY_INDEX = {
    "1": "thumb",
    "2": "index",
    "3": "middle",
    "4": "ring",
    "5": "pinky",
}
RH_FINGERS = {
    "thumb": "thumb",
    "index": "index",
    "middle": "middle",
    "ring": "ring",
    "little": "pinky",
}
MOVABLE_TYPES = {"revolute", "continuous", "prismatic"}


def side_prefix(side: str) -> str:
    return "r" if side == "right" else "l"


def add(mapping: dict[str, str], old: str, new: str) -> None:
    if old in mapping and mapping[old] != new:
        raise ValueError(f"conflicting mapping for {old}: {mapping[old]} vs {new}")
    mapping[old] = new


def normalize_mesh_uri(uri: str) -> str:
    """Convert package:// and legacy absolute mesh references into file:// URIs."""
    legacy_root_map = {
        ROOT / "openarm_description": ROOT / "vendor" / "openarm_description",
        ROOT / "RH56F1": ROOT / "vendor" / "RH56F1",
    }

    package_prefix = "package://"
    if not uri.startswith(package_prefix):
        file_prefix = "file://"
        if uri.startswith(file_prefix):
            path = Path(uri[len(file_prefix) :])
            for old_root, new_root in legacy_root_map.items():
                try:
                    relpath = path.relative_to(old_root)
                except ValueError:
                    continue
                return f"file://{(new_root / relpath).resolve()}"
        return uri

    remainder = uri[len(package_prefix) :]
    package, _, relpath = remainder.partition("/")
    asset_root = ASSET_ROOTS.get(package)
    if asset_root is None or not relpath:
        return uri
    return f"file://{(asset_root / relpath).resolve()}"


def hand_mount_parent_links(root: ET.Element) -> set[str]:
    """Arm links that carry a replacement hand (parent of a ``*_hj_mount`` joint)."""
    parents: set[str] = set()
    for joint in root.findall("joint"):
        name = joint.get("name") or ""
        parent = joint.find("parent")
        if name.endswith("_hj_mount") and parent is not None:
            parents.add(parent.get("link") or "")
    return parents


def strip_stock_gripper_motor(root: ET.Element) -> None:
    """Swap link7 meshes for the cropped variants without the stock-gripper motor.

    Only applies to link7s that carry a replacement hand mount; a link7 with
    the stock gripper attached keeps the stock mesh (the motor is present).
    """
    swap_links = ARM_FLANGE_LINKS & hand_mount_parent_links(root)
    for link in root.findall("link"):
        if link.get("name") not in swap_links:
            continue
        for mesh in link.iter("mesh"):
            uri = mesh.get("filename")
            if not uri:
                continue
            head, sep, base = uri.rpartition("/")
            replacement = STOCK_LINK7_MESH_SWAP.get(base)
            if replacement:
                mesh.set("filename", f"{head}{sep}{replacement}")


def make_self_collision_safe(root: ET.Element, flange_collision_mesh: Path) -> None:
    """Remove the resting-pose penetrations so self-collision can be enabled.

    With articulation self-collision on, PhysX collides all non-adjacent link
    pairs. Two pairs interpenetrate at rest by construction and generate
    phantom forces:
      - link7 <-> *_hl_adapter: the flange bolts insert 4mm into the adapter
        plate (collision approximations lose the bolt holes)
      - link7 <-> *_hl_base: the bolt tips touch the hand mount bottom
    Fix: the hand-mounted link7 collision uses the bolt-free flange-cut mesh
    (visual keeps the bolts), and the fully enclosed adapter plate loses its
    collision geometry (nothing external can ever reach it).
    """
    hand_links = ARM_FLANGE_LINKS & hand_mount_parent_links(root)
    adapter_links = {f"{name[0]}_hl_adapter" for name in hand_links}
    for link in root.findall("link"):
        name = link.get("name")
        if name in hand_links:
            for collision in link.findall("collision"):
                mesh = collision.find("geometry/mesh")
                if mesh is not None:
                    mesh.set("filename", f"file://{flange_collision_mesh}")
        elif name in adapter_links:
            for collision in link.findall("collision"):
                link.remove(collision)


def fit_rh56f1_primitive_collisions(root: ET.Element) -> None:
    """Swap RH56F1 finger-chain collision meshes for fitted primitives."""
    import math

    import numpy as np
    import trimesh

    from gen_fabric_urdfs import mat_to_rpy, rpy_to_mat

    # RH56F1-only: gate on palm_1, which no other asset has (tesollo hands
    # share finger link names like r_hl_thumb_1 and must keep their meshes)
    if not any(link.get("name") in RH_DROP_COLLISION_LINKS for link in root.findall("link")):
        return

    axis_rotation = {
        0: rpy_to_mat(0.0, math.pi / 2.0, 0.0),  # cylinder z -> x
        1: rpy_to_mat(math.pi / 2.0, 0.0, 0.0),  # cylinder z -> -y (symmetric)
        2: np.eye(3),
    }

    for link in root.findall("link"):
        if link.get("name") in RH_DROP_COLLISION_LINKS:
            for collision in link.findall("collision"):
                link.remove(collision)
            continue
        if link.get("name") not in RH_PRIMITIVE_LINKS:
            continue
        for collision in link.findall("collision"):
            mesh_el = collision.find("geometry/mesh")
            if mesh_el is None:
                continue
            path = (mesh_el.get("filename") or "").removeprefix("file://")
            scale = np.array([float(v) for v in (mesh_el.get("scale") or "1 1 1").split()])
            vertices = trimesh.load(path, force="mesh").vertices * scale
            low, high = vertices.min(axis=0), vertices.max(axis=0)
            center, extents = (low + high) / 2.0, high - low

            origin = collision.find("origin")
            old_xyz = np.array([float(v) for v in ((origin.get("xyz") if origin is not None else None) or "0 0 0").split()])
            old_rpy = [float(v) for v in ((origin.get("rpy") if origin is not None else None) or "0 0 0").split()]
            old_rot = rpy_to_mat(*old_rpy)

            geometry = collision.find("geometry")
            assert geometry is not None
            geometry.remove(mesh_el)
            order = np.argsort(extents)[::-1]
            if extents[order[0]] / max(extents[order[1]], 1e-9) > RH_CYLINDER_ELONGATION:
                axis = int(order[0])
                radius = float(extents[order[2]]) / 2.0  # inscribed: smallest cross extent
                ET.SubElement(geometry, "cylinder", {
                    "radius": f"{radius:.6g}", "length": f"{extents[axis]:.6g}",
                })
                new_rot = old_rot @ axis_rotation[axis]
            else:
                ET.SubElement(geometry, "box", {"size": " ".join(f"{v:.6g}" for v in extents)})
                new_rot = old_rot
            new_xyz = old_xyz + old_rot @ center
            if origin is None:
                origin = ET.SubElement(collision, "origin")
            origin.set("xyz", " ".join(f"{v:.6g}" for v in new_xyz))
            origin.set("rpy", " ".join(f"{v:.6g}" for v in mat_to_rpy(new_rot)))


def build_openarm_maps(link_names: set[str], joint_names: set[str]) -> tuple[dict[str, str], dict[str, str]]:
    link_map: dict[str, str] = {}
    joint_map: dict[str, str] = {}

    if "world" in link_names:
        add(link_map, "world", "body_root")
    if "openarm_body_link0" in link_names:
        add(link_map, "openarm_body_link0", "body_link")
    if "openarm_body_world_joint" in joint_names:
        add(joint_map, "openarm_body_world_joint", "body_j_base")

    for side in ("right", "left"):
        s = side_prefix(side)
        for i in range(8):
            old_link = f"openarm_{side}_link{i}"
            if old_link in link_names:
                add(link_map, old_link, f"{s}_al_{i}")
        fixed_joint = f"openarm_{side}_openarm_body_link0_joint"
        if fixed_joint in joint_names:
            add(joint_map, fixed_joint, f"{s}_aj_base")
        for i in range(1, 8):
            old_joint = f"openarm_{side}_joint{i}"
            if old_joint in joint_names:
                add(joint_map, old_joint, f"{s}_aj_{i}")

    return link_map, joint_map


def build_tesollo_maps(
    link_names: set[str], joint_names: set[str]
) -> tuple[dict[str, str], dict[str, str]]:
    link_map: dict[str, str] = {}
    joint_map: dict[str, str] = {}

    variants = [
        {
            "side": "right",
            "link_prefix": "rl",
            "joint_prefix": "rj",
            "base_link": "right_base_link",
            "adapter_joint": "dummy_joint",
            "mount_joint": "mount_right_link7_to_tesollo",
            "alias_link": "right_palm_link",
            "legacy_alias_link": "palm_link",
            "ee_link": "right_palm_ee",
            "legacy_ee_link": "palm_ee",
            "alias_joint": "right_upstream_palm_to_palm_link",
            "legacy_alias_joint": "upstream_palm_to_palm_link",
            "ee_joint": "right_palm_link_to_ee",
            "legacy_ee_joint": "palm_link_to_ee",
        },
        {
            "side": "left",
            "link_prefix": "ll",
            "joint_prefix": "lj",
            "base_link": "left_base_link",
            "adapter_joint": "base_joint2",
            "mount_joint": "mount_left_link7_to_tesollo",
            "alias_link": "left_palm_link",
            "legacy_alias_link": None,
            "ee_link": "left_palm_ee",
            "legacy_ee_link": None,
            "alias_joint": "left_upstream_palm_to_palm_link",
            "legacy_alias_joint": None,
            "ee_joint": "left_palm_link_to_ee",
            "legacy_ee_joint": None,
        },
    ]

    for cfg in variants:
        side = cfg["side"]
        s = side_prefix(side)
        lp = cfg["link_prefix"]
        jp = cfg["joint_prefix"]

        if cfg["base_link"] in link_names:
            add(link_map, cfg["base_link"], f"{s}_hl_mount")
        if f"{lp}_dg_mount" in link_names:
            add(link_map, f"{lp}_dg_mount", f"{s}_hl_adapter")
        if f"{lp}_dg_base" in link_names:
            add(link_map, f"{lp}_dg_base", f"{s}_hl_base")
        if f"{lp}_dg_palm" in link_names:
            add(link_map, f"{lp}_dg_palm", f"{s}_hl_palm")
        for key in ("alias_link", "legacy_alias_link"):
            old = cfg.get(key)
            if old and old in link_names:
                add(link_map, old, f"{s}_hl_palm_alias")
        for key in ("ee_link", "legacy_ee_link"):
            old = cfg.get(key)
            if old and old in link_names:
                add(link_map, old, f"{s}_hl_palm_ee")

        if cfg["mount_joint"] in joint_names:
            add(joint_map, cfg["mount_joint"], f"{s}_hj_mount")
        if cfg["adapter_joint"] in joint_names:
            add(joint_map, cfg["adapter_joint"], f"{s}_hj_adapter")
        if f"{jp}_dg_base" in joint_names:
            add(joint_map, f"{jp}_dg_base", f"{s}_hj_base")
        if f"{jp}_dg_palm" in joint_names:
            add(joint_map, f"{jp}_dg_palm", f"{s}_hj_palm")
        for key in ("alias_joint", "legacy_alias_joint"):
            old = cfg.get(key)
            if old and old in joint_names:
                add(joint_map, old, f"{s}_hj_palm_alias")
        for key in ("ee_joint", "legacy_ee_joint"):
            old = cfg.get(key)
            if old and old in joint_names:
                add(joint_map, old, f"{s}_hj_palm_ee")

        for dg_idx, finger in TESOLLO_FINGER_BY_INDEX.items():
            for segment in range(1, 5):
                old_link = f"{lp}_dg_{dg_idx}_{segment}"
                old_joint = f"{jp}_dg_{dg_idx}_{segment}"
                if old_link in link_names:
                    add(link_map, old_link, f"{s}_hl_{finger}_{segment}")
                if old_joint in joint_names:
                    add(joint_map, old_joint, f"{s}_hj_{finger}_{segment}")
            old_tip_link = f"{lp}_dg_{dg_idx}_tip"
            old_tip_joint = f"{jp}_dg_{dg_idx}_tip"
            if old_tip_link in link_names:
                add(link_map, old_tip_link, f"{s}_hl_{finger}_tip")
            if old_tip_joint in joint_names:
                add(joint_map, old_tip_joint, f"{s}_hj_{finger}_tip")

    return link_map, joint_map


def build_rh56f1_maps(link_names: set[str], joint_names: set[str]) -> tuple[dict[str, str], dict[str, str]]:
    link_map: dict[str, str] = {}
    joint_map: dict[str, str] = {}

    for side in ("right", "left"):
        s = side_prefix(side)
        base = f"rh56f1_{side}"
        old_base_link = f"{base}_base_link"
        if old_base_link in link_names:
            add(link_map, old_base_link, f"{s}_hl_base")
        mount_joint = f"mount_{side}_link7_to_rh56f1"
        if mount_joint in joint_names:
            add(joint_map, mount_joint, f"{s}_hj_mount")

        for i in range(1, 4):
            old_link = f"{base}_plam_{i}"
            old_joint = f"{base}_plam_{i}_joint"
            # The right hand source has a misspelled joint suffix: jont.
            old_joint_typo = f"{base}_plam_{i}_jont"
            if old_link in link_names:
                add(link_map, old_link, f"{s}_hl_palm_{i}")
            if old_joint in joint_names:
                add(joint_map, old_joint, f"{s}_hj_palm_{i}")
            if old_joint_typo in joint_names:
                add(joint_map, old_joint_typo, f"{s}_hj_palm_{i}")
        old_sensor_link = f"{base}_plam_force_sensor"
        old_sensor_joint = f"{base}_plam_force_sensor_joint"
        if old_sensor_link in link_names:
            add(link_map, old_sensor_link, f"{s}_hl_palm_sensor")
        if old_sensor_joint in joint_names:
            add(joint_map, old_sensor_joint, f"{s}_hj_palm_sensor")

        for src_finger, canonical_finger in RH_FINGERS.items():
            max_segment = 4 if src_finger == "thumb" else 2
            for segment in range(1, max_segment + 1):
                old_link = f"{base}_{side}_{src_finger}_{segment}"
                old_joint = f"{base}_{side}_{src_finger}_{segment}_joint"
                if old_link in link_names:
                    add(link_map, old_link, f"{s}_hl_{canonical_finger}_{segment}")
                if old_joint in joint_names:
                    add(joint_map, old_joint, f"{s}_hj_{canonical_finger}_{segment}")
            sensor_link = f"{base}_{src_finger}_force_sensor"
            sensor_joint = f"{base}_{src_finger}_force_sensor_joint"
            tip_link = f"{base}_{src_finger}_tip"
            tip_joint = f"{base}_{src_finger}_tip_joint"
            if sensor_link in link_names:
                add(link_map, sensor_link, f"{s}_hl_{canonical_finger}_sensor")
            if sensor_joint in joint_names:
                add(joint_map, sensor_joint, f"{s}_hj_{canonical_finger}_sensor")
            if tip_link in link_names:
                add(link_map, tip_link, f"{s}_hl_{canonical_finger}_tip")
            if tip_joint in joint_names:
                add(joint_map, tip_joint, f"{s}_hj_{canonical_finger}_tip")

    return link_map, joint_map


def build_stock_gripper_maps(link_names: set[str], joint_names: set[str]) -> tuple[dict[str, str], dict[str, str]]:
    link_map: dict[str, str] = {}
    joint_map: dict[str, str] = {}

    for side in ("right", "left"):
        s = side_prefix(side)
        entries = {
            f"openarm_{side}_hand": f"{s}_hl_gripper_base",
            f"openarm_{side}_hand_tcp": f"{s}_hl_gripper_tcp",
            f"openarm_{side}_left_finger": f"{s}_hl_gripper_left_finger",
            f"openarm_{side}_right_finger": f"{s}_hl_gripper_right_finger",
        }
        for old, new in entries.items():
            if old in link_names:
                add(link_map, old, new)
        joint_entries = {
            f"{side}_openarm_hand_joint": f"{s}_hj_gripper_mount",
            f"openarm_{side}_hand_tcp_joint": f"{s}_hj_gripper_tcp",
            f"openarm_{side}_finger_joint1": f"{s}_hj_gripper_1",
            f"openarm_{side}_finger_joint2": f"{s}_hj_gripper_2",
        }
        for old, new in joint_entries.items():
            if old in joint_names:
                add(joint_map, old, new)

    return link_map, joint_map


def merge_maps(*maps: tuple[dict[str, str], dict[str, str]]) -> tuple[dict[str, str], dict[str, str]]:
    link_map: dict[str, str] = {}
    joint_map: dict[str, str] = {}
    for lm, jm in maps:
        for old, new in lm.items():
            add(link_map, old, new)
        for old, new in jm.items():
            add(joint_map, old, new)
    return link_map, joint_map


def all_names(root: ET.Element) -> tuple[set[str], set[str]]:
    return (
        {elem.attrib["name"] for elem in root.findall("link") if "name" in elem.attrib},
        {elem.attrib["name"] for elem in root.findall("joint") if "name" in elem.attrib},
    )


def rename_tree(root: ET.Element, link_map: dict[str, str], joint_map: dict[str, str],
                robot_name: str) -> None:
    root.attrib["name"] = robot_name

    for link in root.findall("link"):
        name = link.attrib.get("name")
        if name in link_map:
            link.attrib["name"] = link_map[name]

    for joint in root.findall("joint"):
        name = joint.attrib.get("name")
        if name in joint_map:
            joint.attrib["name"] = joint_map[name]

    for elem in root.iter():
        link_ref = elem.attrib.get("link")
        if link_ref in link_map:
            elem.attrib["link"] = link_map[link_ref]
        joint_ref = elem.attrib.get("joint")
        if joint_ref in joint_map:
            elem.attrib["joint"] = joint_map[joint_ref]
        reference = elem.attrib.get("reference")
        if reference in link_map:
            elem.attrib["reference"] = link_map[reference]
        filename = elem.attrib.get("filename")
        if filename:
            elem.attrib["filename"] = normalize_mesh_uri(filename)


def shift_origin_z(parent: ET.Element, dz: float) -> None:
    origin = parent.find("origin")
    if origin is None:
        origin = ET.SubElement(parent, "origin", {"xyz": "0 0 0", "rpy": "0 0 0"})
    xyz = origin.attrib.get("xyz", "0 0 0").split()
    if len(xyz) != 3:
        raise ValueError(f"malformed origin xyz: {origin.attrib.get('xyz')}")
    x, y, z = (float(v) for v in xyz)
    origin.attrib["xyz"] = f"{x:g} {y:g} {z + dz:g}"


def apply_base_origin_fix(root: ET.Element, cropped_meshes: dict[str, Path]) -> None:
    """Move the robot origin from the vendor plate bottom to the plate top.

    Uses pre-cropped/pre-shifted body meshes and lowers everything defined in
    the vendor body frame (inertial COM, arm base joints) by BASE_LIFT_M.
    """
    body = next((l for l in root.findall("link") if l.attrib.get("name") == "body_link"), None)
    if body is None:
        raise ValueError("body_link not found; cannot apply base origin fix")

    for tag, kind in (("visual", "visual"), ("collision", "collision")):
        for elem in body.findall(tag):
            mesh = elem.find("geometry/mesh")
            if mesh is None:
                raise ValueError(f"body_link {tag} has no mesh geometry")
            mesh.attrib["filename"] = f"file://{cropped_meshes[kind]}"

    inertial = body.find("inertial")
    if inertial is not None:
        shift_origin_z(inertial, -BASE_LIFT_M)

    arm_bases = [j for j in root.findall("joint") if j.attrib.get("name") in {"r_aj_base", "l_aj_base"}]
    if len(arm_bases) != 2:
        raise ValueError("expected both r_aj_base and l_aj_base joints")
    for joint in arm_bases:
        shift_origin_z(joint, -BASE_LIFT_M)


def attach_head(root: ET.Element) -> tuple[dict[str, str], dict[str, str]]:
    """Merge the D435i pan/tilt head into the robot, mounted on body_link."""
    head_root = ET.parse(HEAD_URDF).getroot()

    for link in head_root.findall("link"):
        new = copy.deepcopy(link)
        name = new.attrib.get("name")
        if name not in HEAD_LINK_MAP:
            raise ValueError(f"unexpected head link: {name}")
        new.attrib["name"] = HEAD_LINK_MAP[name]
        for mesh in new.iter("mesh"):
            filename = mesh.attrib.get("filename", "")
            if not filename.startswith("../"):
                raise ValueError(f"unexpected head mesh path: {filename}")
            mesh.attrib["filename"] = f"file://{(HEAD_URDF.parent / filename).resolve()}"
        root.append(new)

    for joint in head_root.findall("joint"):
        new = copy.deepcopy(joint)
        name = new.attrib.get("name")
        if name not in HEAD_JOINT_MAP:
            raise ValueError(f"unexpected head joint: {name}")
        new.attrib["name"] = HEAD_JOINT_MAP[name]
        for elem in new.iter():
            link_ref = elem.attrib.get("link")
            if link_ref in HEAD_LINK_MAP:
                elem.attrib["link"] = HEAD_LINK_MAP[link_ref]
        root.append(new)

    mount = ET.SubElement(root, "joint", {"name": "head_j_mount", "type": "fixed"})
    ET.SubElement(mount, "parent", {"link": "body_link"})
    ET.SubElement(mount, "child", {"link": "head_base"})
    ET.SubElement(mount, "origin", {"xyz": HEAD_MOUNT_XYZ, "rpy": "0 0 0"})

    ET.SubElement(root, "link", {"name": "head_cam_view"})
    view = ET.SubElement(root, "joint", {"name": "head_j_cam_view", "type": "fixed"})
    ET.SubElement(view, "parent", {"link": "head_camera"})
    ET.SubElement(view, "child", {"link": "head_cam_view"})
    ET.SubElement(
        view,
        "origin",
        {
            "xyz": " ".join(f"{v:g}" for v in HEAD_CAM_VIEW_XYZ),
            "rpy": " ".join(f"{v:g}" for v in HEAD_CAM_VIEW_RPY),
        },
    )

    return dict(HEAD_LINK_MAP), dict(HEAD_JOINT_MAP)


# ★A URDF link without <inertial> is a "massless frame", but the USD import keeps
#   fixed joints unmerged (tip sensors / palm frames must stay bodies), so every such
#   frame becomes a rigid body - and PhysX gives a body with no mass 1.0 kg (measured
#   2026-09-02: 4 kg of ghost mass at the fingertips, j7 sag 11° vs 4° real). Writing
#   0 does not help either (PhysX rejects zero mass -> 1.0 kg again), so the frames
#   get a token 1e-5 kg (user-set, 2026-09-05: the same URDF feeds fabric/PD models
#   where a zero mass breaks the dynamics) here, in the URDF itself, and every
#   consumer (USD importer, fabric generators, sim2real models) sees the same value.
TOKEN_MASS_KG = 1e-5
TOKEN_INERTIA = 1e-7

# ★Measured hand payloads (kg, per hand, everything past the wrist flange) that the
#   vendor link masses must add up to. DG-5F: user scale measurement 1.763 kg vs vendor
#   URDF 1.685 kg (4.6 % low; sim2real/docs/NEXT_SESSION_RIGHT_2026-08-31.md). The
#   vendor masses are round numbers with no per-part breakdown, so every hand link
#   (and its inertia tensor - same geometry) is scaled by one factor. Assets not
#   listed keep the vendor masses verbatim.
HAND_MASS_TARGET_KG = {"openarm_dg5f-m_bi": 1.763}


def scale_hand_masses(root: ET.Element, target_kg: float) -> dict[str, float]:
    """Scale every ``*_hl_*`` inertial per side so the hand sums to ``target_kg``."""
    factors: dict[str, float] = {}
    for side in ("r", "l"):
        links = [l for l in root.findall("link")
                 if (l.get("name") or "").startswith(f"{side}_hl_") and l.find("inertial") is not None]
        total = sum(float(l.find("inertial/mass").get("value")) for l in links)
        if total <= 0:
            raise ValueError(f"{side} hand has no mass to scale")
        factor = target_kg / total
        for link in links:
            mass = link.find("inertial/mass")
            mass.set("value", f"{float(mass.get('value')) * factor:.6g}")
            inertia = link.find("inertial/inertia")
            if inertia is not None:
                for key, value in list(inertia.attrib.items()):
                    inertia.set(key, f"{float(value) * factor:.6g}")
        factors[side] = factor
    return factors


# ★★2026-09-09 **기본 골자**: 자산은 관절한계 방침을 **명시적으로 선언**해야 한다.
#   벤더 URDF 한계가 실제 가동 범위를 보장하지 않는다는 것이 09.09 에 확인됐다:
#     · `_3/_4` 는 CAD·드라이버 두 사본이 **똑같이 ±1.5708**(대칭 ±90°)을 준다 — 실제
#       PIP/DIP 가 뒤로 90° 젖혀질 리 없으므로 placeholder 다(플랫 effort 7.5 와 같은 성격).
#     · `thumb_1` 하한 −0.384 는 엄지가 손바닥/베이스를 **0.67 mm 파고드는** 각도다.
#   그 한계를 그대로 쓰면 정책이 도달 불가능한 자세를 명령하고, 접촉이 관절을 한계 밖으로
#   밀어낸다(실측 thumb_1 −4.075 rad, 표본 93% 한계 밖).
#   ⇒ 자산을 추가할 때 **빈 dict 라도 반드시 등록**한다. 미등록은 빌드 에러다 —
#     "아직 안 쟀다"와 "잴 필요가 없다"를 구분해서 남기기 위해서다.
#   측정 방법은 docs/ROBOT_ASSET_SPEC.md §2-1. 요지는 둘이다:
#     ①다른 관절은 **0(편 상태)** 로 두고 하나씩 굽힌다(이웃을 극단에 고정하면 조합을 잰다).
#     ②같은 손가락 안쪽 **2-hop 쌍**(`_2↔_4`,`_2↔tip`)을 포함한다 — PhysX 자동 필터는
#       직접 연결된 부모-자식뿐이고, 굴곡 한계를 정하는 건 그 2-hop 쌍이다.
# ══════════════════════════════════════════════════════════════════════════════
# 손 관절 사양 — 출처는 **벤더 공식 사용자 매뉴얼**이다.
#   `DG5F_User_Manual_En_v1.1.4` §3.1(전기 사양) · §3.3.1(모터별 가동범위)
#
# ★왜 URDF 가 아니라 매뉴얼인가. 벤더가 같은 값을 두 곳에서 **다르게** 준다:
#     effort    드라이버 URDF 7.5 N·m   vs  매뉴얼 peak(stall) **2.0 N·m**   → 3.75배 과대
#     velocity  드라이버 URDF 3.142 rad/s vs 매뉴얼 무부하 75 RPM = **7.854** → 2.5배 과소
#     가동범위  7개 관절이 불일치. 대표적으로 `thumb_1` URDF -22~+51° vs 매뉴얼 -22~+77°.
#   URDF 의 7.5 와 π 는 placeholder 로 보인다(전 20관절이 같은 값, π 라는 우연). 매뉴얼은
#   제품 사양서이고 CAD 릴리스와도 일치한다(엄지 상한 CAD 1.3439 rad = 77°). 매뉴얼이 기준이다.
#
# ★부호 규약. 매뉴얼은 모터 기준, URDF 는 링크 기준이라 `thumb_2` 만 방향이 반대다
#   (매뉴얼 0~+155°, URDF 프레임에서는 굴곡이 음수 → -155~0). 나머지 19관절은 같다.
#
# ★과신전(`_3/_4` 음수)은 **자산에서 허용**한다 — 실기가 실제로 되기 때문이다. 정책이 그걸
#   명령하지 못하게 막는 것은 프로필의 `hand_action_limit_override` 몫이다. 물리 한계와
#   액션 범위는 다른 층이고, 섞으면 "실기에 있는 자유도를 sim 이 모른다"가 된다(09.09 확정).
#
# ⚠매뉴얼 정격(연속) 토크는 **0.4 N·m** 이고 2.0 은 스톨(순간)이다. 매뉴얼이 스톨 연속 사용에
#   "급격한 온도 상승·제품 손상"을 경고하므로, 파지 유지 토크는 0.4 근처를 목표로 감시할 것.
# ══════════════════════════════════════════════════════════════════════════════
_D = math.radians

#: 매뉴얼 §3.1 — 전 관절 공통(모터가 20개 모두 같다).
HAND_PEAK_TORQUE_NM = 2.0        # Peak Torque of Each Joint (Stall torque)
HAND_RATED_TORQUE_NM = 0.4       # Rated Torque — 연속 사용 목표(자산에는 안 싣는다)
HAND_NO_LOAD_RAD_S = 75.0 * 2.0 * math.pi / 60.0     # 75 RPM

#: 매뉴얼 §3.3.1 오른손 Motor 1..20 → 관절 접미사. 좌우는 미러라 같은 표를 쓴다.
_DG5F_M_RANGE_DEG: dict[str, tuple[float, float]] = {
    "thumb_1": (-22, 77), "thumb_2": (-155, 0), "thumb_3": (-90, 90), "thumb_4": (-90, 90),
    "index_1": (-31, 20), "index_2": (0, 115), "index_3": (-90, 90), "index_4": (-90, 90),
    "middle_1": (-30, 30), "middle_2": (0, 115), "middle_3": (-90, 90), "middle_4": (-90, 90),
    "ring_1": (-15, 32), "ring_2": (0, 110), "ring_3": (-90, 90), "ring_4": (-90, 90),
    "pinky_1": (0, 60), "pinky_2": (-15, 90), "pinky_3": (-90, 90), "pinky_4": (-90, 90),
}

#: 자산 → 손 관절 사양. **미등록은 빌드 에러**(벤더 URDF placeholder 를 조용히 쓰지 않게).
#: 값은 {정규식: (lower_rad, upper_rad)} 이고, effort/velocity 는 전 손관절 공통이다.
HAND_JOINT_SPEC: dict[str, dict[str, tuple[float, float]] | None] = {
    # 매뉴얼을 아직 대조하지 않은 자산 — None 이면 벤더 URDF 값을 그대로 둔다(사실을 남긴다).
    "openarm_dg5f-m-short_bi": None,
    "openarm_dg5f-s_bi": None,
    "openarm_rh56f1_bi": None,
    "openarm_gripper_bi": None,
    "openarm_dg5f-m_bi": {
        rf"[rl]_hj_{_suffix}$": (_D(_lo), _D(_hi))
        for _suffix, (_lo, _hi) in _DG5F_M_RANGE_DEG.items()
    },
}



def apply_hand_joint_spec(root: ET.Element, asset: str) -> list[str]:
    """손 관절의 한계·effort·velocity 를 **벤더 매뉴얼 값으로 설정**한다.

    구 `restrict_joint_limits` 를 대체한다. 그쪽은 "좁히기만" 했는데, 매뉴얼 값이 드라이버
    URDF 보다 **넓은** 관절이 있어(엄지 대향 51°→77°) 좁히기로는 옮길 수 없다.
    좁히기 전용이던 시절 엄지 대향이 ±9.2° 로 잘려 있었고, 그러면 엄지가 손가락 쪽으로
    돌아오지 못해 **인벨롭 파지가 원리적으로 불가능**하다(09.09 원인 분석).

    미등록 자산은 빌드 에러다. None 이면 벤더 URDF 값을 그대로 둔다(대조 안 한 사실을 남긴다).
    """
    if asset not in HAND_JOINT_SPEC:
        raise RuntimeError(
            f"{asset}: HAND_JOINT_SPEC 에 항목이 없다 — None 이라도 선언할 것.\n"
            "  벤더 드라이버 URDF 의 effort 7.5 / velocity π 는 placeholder 로 보이고,\n"
            "  매뉴얼 §3.1 은 peak 2.0 N·m / 75 RPM 이다. 조용히 URDF 값을 쓰지 않는다.")
    rules = HAND_JOINT_SPEC[asset]
    if rules is None:
        return []
    # ★좌우 미러. 표는 **오른손 기준**(매뉴얼 §3.3.1 Right hand)이고, 왼손은 관절에 따라
    #   부호가 뒤집힌다 — 벌림/대향은 미러(l = -hi..-lo), 굴곡은 그대로다.
    #   어느 쪽인지 **원본 URDF 의 좌우 관계에서 판정**한다. 표에 손으로 적으면 20개를 두 번
    #   적어야 하고, 한 줄만 틀려도 왼손이 조용히 반대로 움직인다(미러 이식 고전 함정).
    _orig: dict[str, tuple[float, float]] = {}
    for _j in root.findall("joint"):
        _n = _j.get("name") or ""
        _l = _j.find("limit")
        if _l is not None and re.fullmatch(r"[rl]_hj_.+", _n):
            _orig[_n] = (float(_l.get("lower")), float(_l.get("upper")))

    def _is_mirrored(name: str) -> bool:
        """이 관절이 원본에서 좌우 부호반전 관계였나. 대칭 구간이면 False(그대로 써도 같다)."""
        if not name.startswith("l_"):
            return False
        mate = "r_" + name[2:]
        if mate not in _orig or name not in _orig:
            raise RuntimeError(f"{name}: 짝 관절 {mate} 이 없어 미러 여부를 판정할 수 없다")
        (llo, lhi), (rlo, rhi) = _orig[name], _orig[mate]
        return abs(llo - (-rhi)) < 1e-6 and abs(lhi - (-rlo)) < 1e-6 and abs(llo + lhi) > 1e-6

    changed: list[str] = []
    seen: set[str] = set()
    for pattern, (new_lo, new_hi) in rules.items():
        matched = False
        for joint in root.findall("joint"):
            name = joint.get("name") or ""
            if not re.fullmatch(pattern, name):
                continue
            matched = True
            seen.add(name)
            limit = joint.find("limit")
            if limit is None:
                raise RuntimeError(f"{name}: <limit> 이 없다 — 사양 적용 불가")
            lo, hi = float(limit.get("lower")), float(limit.get("upper"))
            eff, vel = limit.get("effort"), limit.get("velocity")
            set_lo, set_hi = (-new_hi, -new_lo) if _is_mirrored(name) else (new_lo, new_hi)
            # 리셋(영 자세)이 닫힌 구간 안이어야 한다. 경계는 정상이다.
            if not (set_lo <= 0.0 <= set_hi) or set_lo >= set_hi:
                raise RuntimeError(
                    f"{name}: 매뉴얼 범위 [{set_lo}, {set_hi}] 가 영 자세를 안 품거나 폭이 0 이다")
            limit.set("lower", f"{set_lo:g}")
            limit.set("upper", f"{set_hi:g}")
            limit.set("effort", f"{HAND_PEAK_TORQUE_NM:g}")
            limit.set("velocity", f"{HAND_NO_LOAD_RAD_S:.3f}")
            changed.append(
                f"{name} [{lo:.4f},{hi:.4f}]→[{set_lo:.4f},{set_hi:.4f}] "
                f"eff {eff}→{HAND_PEAK_TORQUE_NM:g} vel {vel}→{HAND_NO_LOAD_RAD_S:.3f}")
        if not matched:
            raise RuntimeError(f"손 관절 사양 규칙 '{pattern}' 이 아무 관절도 못 잡았다")
    # 손 관절인데 표에 없는 것이 있으면 조용히 placeholder 로 남는다 — 시끄럽게 죽인다.
    missed = [j.get("name") for j in root.findall("joint")
              if re.fullmatch(r"[rl]_hj_.+", j.get("name") or "")
              and (j.find("limit") is not None) and j.get("name") not in seen]
    if missed:
        raise RuntimeError(
            f"{asset}: 손 관절 {missed} 가 HAND_JOINT_SPEC 에 안 걸렸다 — "
            "벤더 URDF placeholder 가 그대로 실린다")
    return changed


# ★★2026-09-09 **기본 골자**: 벤더에 없는 **순수 주소지정용 프레임**은 자동으로 뺀다.
#   조건 — ①지오메트리(visual/collision)가 없고 ②들어오는 고정관절이 정확히 1개이며
#   ③앞뒤 조인트 중 하나가 **항등변환**이다. 이런 링크는 기구학적으로 아무 일도 하지
#   않으면서 PhysX 강체만 하나 늘린다. 무질량 강체는 만들 수 없어(1 kg 유령) 토큰 질량
#   1e-5 kg 을 줄 수밖에 없고, 그러면 팔(0.47kg)↔손(1.76kg) 체인에 10⁵ 질량비가 낀다.
#   "sim 에서 무질량·무접촉"을 실제로 얻는 방법은 **링크를 없애는 것**뿐이다(사용자 확정).
#
#   ⚠**링크는 소비처가 없어도 조인트 이름은 쓰인다.** `r_hj_mount` 를 fabric 생성기와
#     기하 계약 테스트가 이름으로 찾고 있었다(09.09 에 40 errors 로 드러남). 그래서
#     앞뒤 조인트 중 **항등인 쪽을 버리고 변환을 가진 쪽 이름을 남긴다.**
#   ⚠이름으로 참조되는 프레임은 `KEEP_ADDRESSING_FRAMES` 에 등록해 보존한다.
KEEP_ADDRESSING_FRAMES = (
    # `robots.py` 가 `palm_ee_body` 로 쓴다. 오프셋(0.028,0,0.04)이 있는 실제 프레임이다.
    "r_hl_palm_ee", "l_hl_palm_ee",
    # 카메라 뷰 원점 — 매니페스트 `camera_view_frame` 이 이름으로 참조한다.
    "head_cam_view",
)


def find_addressing_frames(root: ET.Element) -> list[str]:
    """제거 대상 주소용 프레임을 **규칙으로** 찾는다(이름 하드코딩 금지)."""
    def _identity(joint: ET.Element) -> bool:
        xyz, rpy = _origin_of(joint)
        return max(abs(v) for v in (*xyz, *rpy)) < 1e-9

    found = []
    for link in root.findall("link"):
        name = link.get("name") or ""
        if name in KEEP_ADDRESSING_FRAMES:
            continue
        if link.findall("collision") or link.findall("visual"):
            continue
        incoming = [j for j in root.findall("joint")
                    if j.find("child") is not None and j.find("child").get("link") == name]
        if len(incoming) != 1 or incoming[0].get("type") != "fixed":
            continue                       # 루트 링크·가동관절 자식은 대상이 아니다
        outgoing = [j for j in root.findall("joint")
                    if j.find("parent") is not None and j.find("parent").get("link") == name]
        if not outgoing:
            continue                       # 말단 프레임은 남긴다(이름으로 쓰일 수 있다)
        if _identity(incoming[0]) or (len(outgoing) == 1 and _identity(outgoing[0])):
            found.append(name)
    return found




def _origin_of(joint: ET.Element) -> tuple[list[float], list[float]]:
    o = joint.find("origin")
    xyz = [float(v) for v in (o.get("xyz") if o is not None else "0 0 0").split()]
    rpy = [float(v) for v in (o.get("rpy") if o is not None else "0 0 0").split()]
    return xyz, rpy


def _compose_origins(outer: ET.Element, inner: ET.Element) -> None:
    """`inner` 의 origin 을 `outer ∘ inner` 로 덮어쓴다(부모가 사라질 때 변환 보존)."""
    import numpy as np

    def mat(xyz, rpy):
        cr, cp, cy = np.cos(rpy)
        sr, sp, sy = np.sin(rpy)
        R = np.array([
            [cy * cp, cy * sp * sr - sy * cr, cy * sp * cr + sy * sr],
            [sy * cp, sy * sp * sr + cy * cr, sy * sp * cr - cy * sr],
            [-sp,     cp * sr,                cp * cr],
        ])
        T = np.eye(4); T[:3, :3] = R; T[:3, 3] = xyz
        return T

    T = mat(*_origin_of(outer)) @ mat(*_origin_of(inner))
    R = T[:3, :3]
    pitch = float(np.arctan2(-R[2, 0], np.hypot(R[0, 0], R[1, 0])))
    roll = float(np.arctan2(R[2, 1], R[2, 2]))
    yaw = float(np.arctan2(R[1, 0], R[0, 0]))
    o = inner.find("origin")
    if o is None:
        o = ET.SubElement(inner, "origin")
    o.set("xyz", " ".join(f"{v:.9g}" for v in T[:3, 3]))
    o.set("rpy", " ".join(f"{v:.9g}" for v in (roll, pitch, yaw)))


def drop_addressing_frames(root: ET.Element) -> list[str]:
    """`find_addressing_frames()` 가 찾은 링크를 제거하고 고정변환을 보존한다.

    ★어느 조인트 **이름**을 남기는가가 중요하다. 링크는 소비처가 없어도 그 링크에
      붙은 조인트 이름은 쓰인다 — `r_hj_mount` 는 fabric 생성기(`gen_fabric_urdfs.py`)와
      기하 계약 테스트(`test_tesollo_mount_flush_on_link7_flange`)가 이름으로 찾는다.
      그래서 **항등변환인 쪽을 버리고 변환을 가진 쪽을 남긴다**:
        mount      : 들어오는 `r_hj_mount`(z 0.0495, yaw −90°) 유지, 나가는 항등 조인트 삭제
        palm_alias : 들어오는 항등 `r_hj_palm_alias` 삭제, 나가는 `r_hj_palm_ee` 에 합성
    """
    def _is_identity(joint: ET.Element) -> bool:
        xyz, rpy = _origin_of(joint)
        return max(abs(v) for v in (*xyz, *rpy)) < 1e-9

    dropped = []
    for name in find_addressing_frames(root):
        link = next((l for l in root.findall("link") if l.get("name") == name), None)
        if link is None:
            continue
        if link.findall("collision") or link.findall("visual"):
            raise RuntimeError(f"{name}: 지오메트리가 있는 링크는 주소용 프레임이 아니다 — 제거 거부")
        incoming = [j for j in root.findall("joint")
                    if j.find("child") is not None and j.find("child").get("link") == name]
        outgoing = [j for j in root.findall("joint")
                    if j.find("parent") is not None and j.find("parent").get("link") == name]
        if len(incoming) != 1 or incoming[0].get("type") != "fixed":
            raise RuntimeError(f"{name}: 들어오는 고정관절이 정확히 1개가 아니다 — 제거 거부")
        j_in = incoming[0]
        parent = j_in.find("parent").get("link")

        if _is_identity(j_in):
            # 들어오는 쪽이 잉여 → 버리고, 나가는 조인트들이 부모를 직접 물게 한다.
            for j in outgoing:
                _compose_origins(j_in, j)
                j.find("parent").set("link", parent)
            root.remove(j_in)
        else:
            # 들어오는 조인트 이름을 살린다. 나가는 쪽은 항등이어야 버릴 수 있다.
            if len(outgoing) != 1:
                raise RuntimeError(
                    f"{name}: 변환을 가진 프레임은 자식이 정확히 1개여야 한다(현재 {len(outgoing)})")
            j_out = outgoing[0]
            if not _is_identity(j_out):
                raise RuntimeError(
                    f"{name}: 앞뒤 조인트가 모두 비항등이라 어느 이름을 남길지 정할 수 없다")
            j_in.find("child").set("link", j_out.find("child").get("link"))
            root.remove(j_out)
        root.remove(link)
        dropped.append(name)
    return dropped


def give_massless_frames_token_mass(root: ET.Element) -> list[str]:
    """Links without <inertial> AND links whose vendor mass is below the token
    (RH56F1 ships its 20 sensor/tip links with mass 0 and a zero tensor - PhysX
    would make each a 1 kg body) both end up at the token mass/inertia."""
    fixed = []
    for link in root.findall("link"):
        inertial = link.find("inertial")
        if inertial is not None:
            mass = inertial.find("mass")
            if mass is not None and float(mass.get("value") or 0.0) >= TOKEN_MASS_KG:
                continue
            link.remove(inertial)
        inertial = ET.SubElement(link, "inertial")
        ET.SubElement(inertial, "origin", {"xyz": "0 0 0", "rpy": "0 0 0"})
        ET.SubElement(inertial, "mass", {"value": f"{TOKEN_MASS_KG:g}"})
        ET.SubElement(inertial, "inertia", {
            "ixx": f"{TOKEN_INERTIA:g}", "ixy": "0", "ixz": "0",
            "iyy": f"{TOKEN_INERTIA:g}", "iyz": "0", "izz": f"{TOKEN_INERTIA:g}"})
        fixed.append(link.get("name") or "")
    return fixed


def sorted_joints(root: ET.Element) -> list[ET.Element]:
    joints = list(root.findall("joint"))
    by_name = {j.attrib["name"]: j for j in joints}
    ordered_names: list[str] = []

    for prefix in ("r", "l"):
        for name in [f"{prefix}_aj_base"] + [f"{prefix}_aj_{i}" for i in range(1, 8)]:
            if name in by_name:
                ordered_names.append(name)
        hand_names = hand_kinematic_order(prefix)
        ordered_names.extend([name for name in hand_names if name in by_name])

    for name in HEAD_JOINT_ORDER:
        if name in by_name:
            ordered_names.append(name)

    if "body_j_base" in by_name:
        ordered_names.insert(0, "body_j_base")

    seen = set(ordered_names)
    # Keep any unexpected joints deterministic and visible after the canonical blocks.
    ordered_names.extend(sorted(name for name in by_name if name not in seen))
    return [by_name[name] for name in ordered_names]


def sorted_links(root: ET.Element) -> list[ET.Element]:
    links = list(root.findall("link"))
    by_name = {l.attrib["name"]: l for l in links}
    ordered_names: list[str] = []

    for name in ["body_root", "body_link"]:
        if name in by_name:
            ordered_names.append(name)
    for prefix in ("r", "l"):
        ordered_names.extend([name for name in [f"{prefix}_al_{i}" for i in range(8)] if name in by_name])
        ordered_names.extend([name for name in hand_link_order(prefix) if name in by_name])
    ordered_names.extend([name for name in HEAD_LINK_ORDER if name in by_name])

    seen = set(ordered_names)
    ordered_names.extend(sorted(name for name in by_name if name not in seen))
    return [by_name[name] for name in ordered_names]


def hand_kinematic_order(prefix: str) -> list[str]:
    names = [
        f"{prefix}_hj_mount",
        f"{prefix}_hj_adapter",
        f"{prefix}_hj_base",
        f"{prefix}_hj_palm",
        f"{prefix}_hj_palm_alias",
        f"{prefix}_hj_palm_ee",
        f"{prefix}_hj_palm_1",
        f"{prefix}_hj_palm_2",
        f"{prefix}_hj_palm_3",
        f"{prefix}_hj_palm_sensor",
        f"{prefix}_hj_gripper_mount",
        f"{prefix}_hj_gripper_tcp",
        f"{prefix}_hj_gripper_1",
        f"{prefix}_hj_gripper_2",
    ]
    for finger in FINGER_NAMES:
        names.extend([f"{prefix}_hj_{finger}_{i}" for i in range(1, 5)])
        names.extend([f"{prefix}_hj_{finger}_sensor", f"{prefix}_hj_{finger}_tip"])
    return names


def hand_link_order(prefix: str) -> list[str]:
    names = [
        f"{prefix}_hl_mount",
        f"{prefix}_hl_adapter",
        f"{prefix}_hl_base",
        f"{prefix}_hl_palm",
        f"{prefix}_hl_palm_alias",
        f"{prefix}_hl_palm_ee",
        f"{prefix}_hl_palm_1",
        f"{prefix}_hl_palm_2",
        f"{prefix}_hl_palm_3",
        f"{prefix}_hl_palm_sensor",
        f"{prefix}_hl_gripper_base",
        f"{prefix}_hl_gripper_tcp",
        f"{prefix}_hl_gripper_left_finger",
        f"{prefix}_hl_gripper_right_finger",
    ]
    for finger in FINGER_NAMES:
        names.extend([f"{prefix}_hl_{finger}_{i}" for i in range(1, 5)])
        names.extend([f"{prefix}_hl_{finger}_sensor", f"{prefix}_hl_{finger}_tip"])
    return names


def reorder_top_level(root: ET.Element) -> None:
    non_links_joints = [copy.deepcopy(e) for e in list(root) if e.tag not in {"link", "joint"}]
    links = [copy.deepcopy(e) for e in sorted_links(root)]
    joints = [copy.deepcopy(e) for e in sorted_joints(root)]
    root[:] = non_links_joints + links + joints


def control_joint_order(root: ET.Element) -> list[str]:
    by_name = {j.attrib["name"]: j for j in root.findall("joint")}
    order: list[str] = []
    for prefix in ("r", "l"):
        order.extend([f"{prefix}_aj_{i}" for i in range(1, 8) if f"{prefix}_aj_{i}" in by_name])
        for finger in FINGER_NAMES:
            for i in range(1, 5):
                name = f"{prefix}_hj_{finger}_{i}"
                joint = by_name.get(name)
                if (
                    joint is not None
                    and joint.attrib.get("type") in MOVABLE_TYPES
                    and joint.find("mimic") is None
                ):
                    order.append(name)
        for name in [f"{prefix}_hj_gripper_1", f"{prefix}_hj_gripper_2"]:
            joint = by_name.get(name)
            if joint is not None and joint.attrib.get("type") in MOVABLE_TYPES and joint.find("mimic") is None:
                order.append(name)
    return order


def kinematic_joint_order(root: ET.Element) -> list[str]:
    return [j.attrib["name"] for j in sorted_joints(root)]


def link_order(root: ET.Element) -> list[str]:
    return [l.attrib["name"] for l in sorted_links(root)]


def validate(root: ET.Element, control_order: list[str]) -> None:
    link_names = [l.attrib["name"] for l in root.findall("link")]
    joint_names = [j.attrib["name"] for j in root.findall("joint")]
    if len(link_names) != len(set(link_names)):
        raise ValueError("duplicate link names after canonical rename")
    if len(joint_names) != len(set(joint_names)):
        raise ValueError("duplicate joint names after canonical rename")

    link_set = set(link_names)
    joint_by_name = {j.attrib["name"]: j for j in root.findall("joint")}
    for joint in root.findall("joint"):
        parent = joint.find("parent")
        child = joint.find("child")
        if parent is not None and parent.attrib.get("link") not in link_set:
            raise ValueError(f"joint {joint.attrib['name']} references missing parent {parent.attrib.get('link')}")
        if child is not None and child.attrib.get("link") not in link_set:
            raise ValueError(f"joint {joint.attrib['name']} references missing child {child.attrib.get('link')}")
    for name in control_order:
        joint = joint_by_name.get(name)
        if joint is None:
            raise ValueError(f"control joint missing from URDF: {name}")
        if joint.attrib.get("type") not in MOVABLE_TYPES:
            raise ValueError(f"control joint is not movable: {name}")
        if joint.find("mimic") is not None:
            raise ValueError(f"control joint is a mimic joint: {name}")


def relative_to_root(path: Path) -> str:
    """Repo-relative when possible (tests generate into a temp dir outside ROOT)."""
    return str(path.relative_to(ROOT)) if path.is_relative_to(ROOT) else str(path)


def yaml_list(values: Iterable[str], indent: int = 2) -> str:
    pad = " " * indent
    values = list(values)
    if not values:
        return f"{pad}[]\n"
    return "".join(f"{pad}- {value}\n" for value in values)


def yaml_map(mapping: dict[str, str], indent: int = 2) -> str:
    pad = " " * indent
    if not mapping:
        return f"{pad}{{}}\n"
    return "".join(f"{pad}{old}: {new}\n" for old, new in sorted(mapping.items()))


def write_manifest(
    output_path: Path,
    source_path: Path,
    urdf_path: Path,
    root: ET.Element,
    link_map: dict[str, str],
    joint_map: dict[str, str],
) -> None:
    control = control_joint_order(root)
    kinematic = kinematic_joint_order(root)
    fixed = [
        j.attrib["name"]
        for j in root.findall("joint")
        if j.attrib.get("type") == "fixed"
    ]
    links = link_order(root)

    text = []
    text.append("# Generated by tools/generate_rl_urdf.py. Do not edit by hand.\n")
    text.append(f"source_urdf: {relative_to_root(source_path)}\n")
    text.append(f"generated_urdf: {relative_to_root(urdf_path)}\n")
    text.append(f"asset: {urdf_path.stem}\n")
    # USD import contract (tools/build_usd.py reads this): OpenArm body/arm/head/
    # stock-gripper links are always plain convex hulls. Dexterous hand links keep
    # convex decomposition **except** for assets in HAND_HULL_ASSETS, where the
    # vendor's own Isaac conversion config (convex_hull) governs - see that constant.
    text.append("collision_approximation:\n")
    text.append(f"  default: {collider_default(urdf_path.stem.removesuffix('_rl'))}\n")
    text.append("  convex_hull_links:\n")
    text.append(yaml_list(convex_hull_links(root), indent=2))
    text.append("schema:\n")
    text.append("  body_root: stage-level root link with no geometry\n")
    text.append("  body_link: openarm physical base link\n")
    text.append("  r_aj_N/l_aj_N: right/left OpenArm movable arm joints\n")
    text.append("  r_hj_*/l_hj_*: right/left hand joints, including fixed mount/base/palm/sensor joints\n")
    text.append("  r_al_N/l_al_N: right/left OpenArm arm links\n")
    text.append("  r_hl_*/l_hl_*: right/left hand links\n")
    text.append("  head_*: D435i pan/tilt head; head_j_pan/head_j_tilt are revolute but stay out of control_joint_order\n")
    text.append("  head_cam_view: camera view origin frame (+X = viewing direction, +Z up), fixed to head_camera\n")
    text.append(f"  origin note: robot origin sits at the mount plate TOP (vendor origin +8mm); head (head_v1, Fusion 2026-09-05) mounts at z=+{HEAD_MOUNT_Z:g}m — physical mount height unverified (B4); body geometry is cut at the head base plate underside z={BODY_TOP_CROP_Z:g}m (vendor head housing removed)\n")
    text.append("camera_view_frame:\n")
    text.append("  link: head_cam_view\n")
    text.append("  parent_link: head_camera\n")
    text.append(f"  rgb_lens_usd_frame: {HEAD_RGB_LENS_FRAME}  # head_v1.usda label of the aperture that is the RGB lens (hand-eye 2026-09-05)\n")
    text.append(f"  xyz: [{', '.join(f'{v:g}' for v in HEAD_CAM_VIEW_XYZ)}]\n")
    text.append(f"  rpy: [{', '.join(f'{v:g}' for v in HEAD_CAM_VIEW_RPY)}]\n")
    # D435i optical origins in the head_camera frame (head_v1 Fusion geometry).
    # Documentation only — no USD frame is created for them.
    text.append("camera_optical_frames:\n")
    text.append("  parent_link: head_camera\n")
    for frame, xyz in HEAD_OPTICAL_FRAMES.items():
        text.append(f"  {frame}: [{', '.join(f'{v:g}' for v in xyz)}]\n")
    text.append("  convention: +X viewing direction, +Z up (robot frame; not ROS optical)\n")
    text.append("control_joint_order:\n")
    text.append(yaml_list(control))
    text.append("kinematic_joint_order:\n")
    text.append(yaml_list(kinematic))
    text.append("fixed_joint_order:\n")
    text.append(yaml_list(fixed))
    text.append("link_order:\n")
    text.append(yaml_list(links))
    text.append("source_to_canonical_joints:\n")
    text.append(yaml_map(joint_map))
    text.append("source_to_canonical_links:\n")
    text.append(yaml_map(link_map))
    output_path.write_text("".join(text), encoding="utf-8")


def generate_one(name: str, source_path: Path) -> tuple[Path, Path]:
    tree = ET.parse(source_path)
    root = tree.getroot()
    link_names, joint_names = all_names(root)
    link_map, joint_map = merge_maps(
        build_openarm_maps(link_names, joint_names),
        build_stock_gripper_maps(link_names, joint_names),
        build_tesollo_maps(link_names, joint_names),
        build_rh56f1_maps(link_names, joint_names),
    )

    rename_tree(root, link_map, joint_map, asset_robot_name(name))
    strip_stock_gripper_motor(root)
    make_self_collision_safe(root, ensure_link7_flange_mesh())
    fit_rh56f1_primitive_collisions(root)
    apply_base_origin_fix(root, ensure_cropped_meshes(top_z_m=BODY_TOP_CROP_Z))
    if name in HAND_MASS_TARGET_KG:
        factors = scale_hand_masses(root, HAND_MASS_TARGET_KG[name])
        print(f"[{name}] hand masses scaled to {HAND_MASS_TARGET_KG[name]} kg "
              f"(x{factors['r']:.4f} / x{factors['l']:.4f})")
    head_link_map, head_joint_map = attach_head(root)
    link_map, joint_map = merge_maps((link_map, joint_map), (head_link_map, head_joint_map))
    for _line in apply_hand_joint_spec(root, name):
        print(f"[{name}] 관절한계 축소 {_line}")
    drop_addressing_frames(root)      # ★토큰 질량 부여 **전에** — 없앨 링크에 질량을 줄 이유가 없다
    give_massless_frames_token_mass(root)
    reorder_top_level(root)
    control = control_joint_order(root)
    validate(root, control)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    urdf_path = OUT_DIR / f"{name}_rl.urdf"
    manifest_path = OUT_DIR / f"{name}_rl_manifest.yaml"

    ET.indent(tree, space="  ")
    tree.write(urdf_path, encoding="utf-8", xml_declaration=True)
    write_manifest(manifest_path, source_path, urdf_path, root, link_map, joint_map)
    return urdf_path, manifest_path


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "names",
        nargs="*",
        help="Optional source names to generate. Defaults to all stable source URDFs.",
    )
    parser.add_argument(
        "--skip-audit",
        action="store_true",
        help="Skip the self-collision audit after generation (used by fast tests).",
    )
    args = parser.parse_args(argv)

    invalid = [name for name in args.names if name not in SOURCES]
    if invalid:
        parser.error(f"unknown source name(s): {', '.join(invalid)}")
    names = args.names or list(SOURCES.keys())
    generated: list[tuple[Path, Path]] = []
    for name in names:
        urdf_path, manifest_path = generate_one(name, SOURCES[name])
        generated.append((urdf_path, manifest_path))
        print(f"generated {relative_to_root(urdf_path)}")
        print(f"generated {relative_to_root(manifest_path)}")

    if not args.skip_audit:
        import audit_self_collision

        ok = True
        for urdf_path, manifest_path in generated:
            # Zero pose plus registered task homes (tools/audit_poses.yaml):
            # near-contact pairs can appear only at a task home.
            pose_findings = audit_self_collision.audit_asset(urdf_path)
            all_findings: list = []
            for pose_name, findings in pose_findings.items():
                ok &= audit_self_collision.report(f"{urdf_path.stem}@{pose_name}", findings)
                all_findings.extend(findings)
            # tools/build_usd.py turns these into PhysX collision filters;
            # WARN pairs are unioned across poses and left/right symmetrized.
            pairs = audit_self_collision.filtered_pairs(
                all_findings, audit_self_collision.urdf_link_names(urdf_path))
            with manifest_path.open("a", encoding="utf-8") as f:
                f.write("self_collision_filtered_pairs:"
                        "  # audited near-contact/nested pairs -> USD collision filters\n")
                f.writelines(f"- [{a}, {b}]\n" for a, b in pairs)
        if not ok:
            print("self-collision audit FAILED - asset(s) interpenetrate at rest", file=sys.stderr)
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
